import Head from 'next/head'
import Button from '@mui/material/Button';
import styles from '../styles/Home.module.css'
import TextField from '@mui/material/TextField';
import InputAdornment from '@mui/material/InputAdornment';
import SearchIcon from '@mui/icons-material/Search';
import Link from '@mui/material/Link';
import IconButton from '@mui/material/IconButton';
import BookIcon from '@mui/icons-material/Book';
import Footer from '../components/footer';
import Book from "../components/book.js";
import React from 'react';
import AccountCircleIcon from '@mui/icons-material/AccountCircle';
import Divider from '@mui/material/Divider';
import Grid from '@mui/material/Grid';
import BookDisplay from '../components/book_display';
import SearchBar from '../components/searchbar';
import LoginItems from "../components/loginitems"
import Header from "../components/header"



export default function Home({ books }) {

  return (
    <div className={styles.container}>
      <Head>
        <title>bkRoad</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* search + cart */}
      {/* <div className={styles.topcontainer}>
        <SearchBar />
        <LoginItems />
      </div> */}
      <Header />

      <h1>Explore Your Personalized Recommendations</h1>
      <div className={styles.bookdisplay}>
      <BookDisplay books={books}/>
      </div>

      <Footer />
    </div>
  )
} 

export async function getServerSideProps(context) {
  const books = [
      {
          title: "The Queen of Paris: A Novel of Coco Chanel",
          author: "Pamela Binnings Ewen" ,
          imageURL: "https://contentcafe2.btol.com/ContentCafe/Jacket.aspx?UserID=NYPL49807&Password=CC68707&Return=1&Type=L&Value=9781982546939&erroroverride=1",
          description: "Legendary fashion designer Coco Chanel is revered for her sophisticated style -- the iconic little black dress -- and famed for her intoxicating perfume Chanel No. 5. Yet behind the public persona is a complicated woman of intrigue, shadowed by mysterious rumors. The Queen of Paris, the new novel from award-winning author Pamela Binnings Ewen, vividly imagines the hidden life of Chanel during the four years of Nazi occupation in Paris in the midst of WWII -- as discovered in recently unearthed wartime files.",
          status: "In stock"            
      },
      {
          title: "The wonders",
          author: "Medel, Elena" ,
          imageURL: "https://contentcafe2.btol.com/ContentCafe/Jacket.aspx?UserID=NYPL49807&Password=CC68707&Return=1&Type=L&Value=9781643753027&erroroverride=1",
          description: "Through the rich inner lives of two ordinary, unforgettable women, award-winning Spanish poet Elena Medel brings a half-century of the feminist movement to life, revealing the simmering truth that money is ultimately the limiting factor in most women's lives",
          status: "Not available"          
      },
      {
          title: "East of hounslow",
          author: "Khurrum Rahman" ,
          imageURL: "https://contentcafe2.btol.com/ContentCafe/Jacket.aspx?UserID=NYPL49807&Password=CC68707&Return=1&Type=L&Value=9780008384661&erroroverride=1",
          description: "No description available",
          status: "In stock"
      }
  ]

  return {
      props: {
          books
      }
  }
}