import Head from 'next/head'
import React from 'react';
import Footer from '../components/footer';
import styles from '../styles/Settings.module.css';
import Stack from '@mui/material/Stack';
import TextField from '@mui/material/TextField';
import Button from '@mui/material/Button';
import Select from '@mui/material/Select';
import Snackbar from '@mui/material/Snackbar';
import IconButton from '@mui/material/IconButton';
import CloseIcon from '@mui/icons-material/Close';

export default class Settings extends React.Component {

  constructor(props) {
    super(props);
    this.handleSubmit = this.handleSubmit.bind(this);
    this.handleChange = this.handleChange.bind(this);
    this.handleToClose = this.handleToClose.bind(this);
    this.state = {name: '', email: '', password: '', address: '', open: false, setOpen: false, showSnacbar: true};
  }
  
  handleToClose = (event, reason) => {
    if ("clickaway" == reason) return;
    this.setState({setOpen: false, open: false})
  };
  
  handleChange(event) { 
    if (event.target.id == "name") {
      this.setState({name: event.target.value});
    }
    else if (event.target.id == "email") { 
      this.setState({email: event.target.value});
    }
    else if (event.target.id == "password") { 
      this.setState({password: event.target.value});
    }
    else { //address
      this.setState({address: event.target.value});
    }
  }

  handleSubmit(event) {
    console.log("Clicked button");
    this.setState({setOpen: true, open: true})
    event.preventDefault();
  }

  render()
  {  
    return (
      <div className={styles.container}>
        <Head>
          <title>bkRoad</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
    
        <div>
          <h2>Account Information</h2>
          
          <form onSubmit={this.handleSubmit}>
            <Stack spacing={2}>
              <p>Name</p>
              <TextField className={styles.textfield} id="name" variant="outlined" size="small" fullWidth={false} onChange={this.handleChange}/>
              <p>Email</p>
              <TextField className={styles.textfield} id="email" variant="outlined" size="small" fullWidth={false} onChange={this.handleChange}/>
              <p>Password</p>
              <TextField className={styles.textfield} id="password" variant="outlined" size="small" fullWidth={false} onChange={this.handleChange}/>
              <p>Address</p>
              <TextField className={styles.textfield} id="address" variant="outlined" size="small" fullWidth={false} onChange={this.handleChange}/>
              <Button className={styles.savesettings} variant="contained" type="submit"> Save Changes</Button>
              <Snackbar 
                anchorOrigin={{
                  horizontal: "left",
                  vertical: "bottom",
                }}
                open={this.state.open}
                autoHideDuration={5000}
                message="Settings Saved"
                onClose={this.handleToClose}
                action={
                <React.Fragment>
                  <IconButton
                    size="small"
                    aria-label="close"
                    color="inherit"
                    onClick={this.handleToClose}
                  >
                  <CloseIcon fontSize="small" />
                  </IconButton>
                </React.Fragment>
                
                }
              />
            </Stack>
          </form>

        </div>     
  
        <Footer />
      
      </div>
    )
  }
}
